<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SonyBraviaControl</AssemblyName>
    <RootNamespace>SonyBraviaControl</RootNamespace>
    <ApplicationIcon>Assets\SonyBraviaControl.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
